FROM ubuntu:latest
LABEL maintainer="Liliya233"
ENV TIME_ZONE Asia/Shanghai
RUN sed -i 's/archive.ubuntu.com/mirrors.bfsu.edu.cn/g' /etc/apt/sources.list \
    && apt-get -yq update \
    && apt-get install ca-certificates -y \
    && apt-get install -y tzdata \
    && ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata \
    && apt-get clean \
    && rm -rf /tmp/*
WORKDIR /workspace
